apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline10java-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /srv/pipeline10java.pv