apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline10java-pvc
  namespace: bank-production-v10
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pipeline10java-pv
  storageClassName: manual