apiVersion: v1
kind: Service
metadata:
  name: pipeline8Trivy-service
  namespace: bank-production
spec:
  type: ClusterIP
  selector:
    app: pipeline8Trivy-app
  ports:
    - port: 80
      targetPort: 80